# Generated by Django 3.2.6 on 2023-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231228_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_no', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Inventory_data',
            },
        ),
        migrations.DeleteModel(
            name='Inventory_data',
        ),
    ]
