# Generated by Django 3.2.6 on 2023-12-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231228_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='model1',
            name='Location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='model1',
            name='Inventory_no',
            field=models.TextField(blank=True),
        ),
    ]
