# Generated by Django 3.2.6 on 2023-12-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231228_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_no', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=8, max_digits=8)),
                ('Purchase_date', models.DateTimeField()),
                ('Active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
