# Generated by Django 3.2.6 on 2023-12-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_no', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('End_user', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Brand', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('Acq_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.DeleteModel(
            name='Model1',
        ),
    ]
